config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_actions.html.erb
<% if current_user %>
<nav class="row microposts-actions" id="micropost-actions-<%= micropost.id %>">
  <ul class="nav">
  <li class="micropost-action like-button">
     <% if current_user.likes?(micropost) %>
        <%= form_for(current_user.likes.find_by(micropost_id: micropost.id), :html => { :method => :delete, :remote => true }) do |f| %>
          <div><%= hidden_field_tag :micropost, micropost %></div>
            <%= button_tag(type: "submit", class: "btn btn-link") do %>
             <span>
               <i class="glyphicon glyphicon-heart"></i>
               <span class="micropost-likes-count-<%micropost.id %>">
                <%= micropost.likes.count %>
               </span>
             </span>
            <% end %>
          <% end %>
      <% else %>
        <%= form_for(current_user.likes.build, method: :post, remote: true) do |f| %>
          <div><%= hidden_field_tag :micropost_id, micropost.id %></div>
          <%= button_tag(type: "submit", class: "btn") do %>
             <span>
               <i class="glyphicon glyphicon-heart-empty"></i>
               <span class="micropost-likes-count-<%micropost.id %>">
                  <%= micropost.likes.count == 0 ? "" : micropost.likes.count %>
               </span>
             </span>
          <% end %>
        <% end %>
    <% end %>
  </li>
  </ul>
</nav>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
    $('#micropost_picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>